### ISSUE TITLE
ReportPortal.Shared.Context.Current.Log not working with NUnit.Engine > 3.15.2

### ISSUE THREAD

**Issue by shatulsky** [reportportal/agent-net-nunit#87] opened 2023-01-26 13:44 UTC
Updating NUnit.Engine to the version greater than 3.15.2 breaks ReportPortal.Shared.Context.Current.Log

Packages versions we currently have:
```
<TargetFramework>net7.0</TargetFramework>

<PackageReference Include="MSTest.TestFramework" Version="3.0.2" />
<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.1" />
<PackageReference Include="NUnit" Version="3.13.3" />
<PackageReference Include="NUnit.Engine" Version="3.15.2" />
<PackageReference Include="NUnit3TestAdapter" Version="4.3.1" />
<PackageReference Include="ReportPortal.NUnit" Version="4.4.1" />
<PackageReference Include="ReportPortal.Shared" Version="3.3.0" />
```

Test example:
```
[Test]
public void Log_Test()
{
    ReportPortal.Shared.Context.Launch.Log.Info("launch info");
    ReportPortal.Shared.Context.Launch.Log.Error("launch error");

    ReportPortal.Shared.Context.Current.Log.Info("current info");
    ReportPortal.Shared.Context.Current.Log.Error("current error");

    throw new ArgumentException("Exception");
}
```

3.15.2 version output:
![image](https://user-images.githubusercontent.com/22248285/214846910-cb49b8e6-6330-4388-bf06-cce13cbb6ced.png)

After updating NUnit.Engine version greater than 3.15.2  - the only exception throw is shown on RP UI
![image](https://user-images.githubusercontent.com/22248285/214847135-393d8f18-2b58-420b-bbe5-a57415982df4.png)

**Comment by nvborisenko** [comment] 2023-01-27 10:36
Reproduced. Logs are not coming to RP using `ReportPortal.Shared.Context.Launch.Log.*("")` in case of installing `NUnit.Engine v16+`.

**Comment by Aleh-Yanushkevich** [comment] 2023-02-22 10:49
@shatulsky sorry for delay. After investigation we found, that assembly with `ReportPortal.NUnitExtension.LogHandler` class, which is responsible for sending logs, is loaded twice to app domain. And due to this fact, extension manager is not able to register `LogMessageHandler`.

 It's an issue on `NUnit.Engine` side and we prepared a solution for reproducing a bug, but found that a some time ago new version of `NUnit.Engine` was release (3.16.3). And issue with incorrect loading into app domain is gone.
 
 Could you please try to increase version of `NUnit.Engine` to 3.16.3 and let us know if it helps you?

**Comment by shatulsky** [comment] 2023-02-22 11:34
Hello @Aleh-Yanushkevich! Thx for the response.
Updating NUnit.Engine version (3.15.2 -> 3.16.3) in my solution - breaks the building of System.IServiceProvider with this error - 
![image](https://user-images.githubusercontent.com/22248285/220608018-5d875a4e-68f8-47d4-8cf2-76f4fad2fd41.png)
So I am not able to confirm the fix

**Comment by Aleh-Yanushkevich** [comment] 2023-02-22 12:19
@shatulsky have you changed anything else except version of NUnit.Engine? Because according to exception, ILogger has not been resolved correctly, which mandatory for ApiClient. `NUnit.Engine` couldn't affect these dependencies.

**Comment by shatulsky** [comment] 2023-02-22 12:22
@Aleh-Yanushkevich 
The only change that makes DI break is updating of NUnit.Engine

**Comment by nvborisenko** [comment] 2023-02-22 12:34
Seems the issue is not related to Report Portal anymore. Can you try to install `NUnit.Engine.Api` package instead of `NUnit.Engine`? At least it should resolve current issues. If it works, then we will close this issue.

And I suggest to post new issue about your DI containers to NUnit core team, because most likely you will face this issue in upcoming new version of `NUnit.TestAdapter`.

**Comment by shatulsky** [comment] 2023-02-22 12:46
Using `NUnit.Engine.Api` `3.16.3` instead of `NUnit.Engine` fixed DI issue.
So now I am able to use the latest version of all related to tests packages.
![image](https://user-images.githubusercontent.com/22248285/220622590-650260a5-920b-4e16-beb8-621d16a9afea.png)
And report portal logging is also working
![image](https://user-images.githubusercontent.com/22248285/220623202-71951603-d7d5-4d37-983b-2e9428d02003.png)
@nvborisenko, @Aleh-Yanushkevich thx for the help!

**Comment by Aleh-Yanushkevich** [comment] 2023-02-22 12:53
@Aleh-Yanushkevich you're welcome!

**Closed by Aleh-Yanushkevich** 2023-02-22 12:53 UTC
Labels: bug

**Comment by nvborisenko** [comment] 2023-03-01 21:47
Related to https://github.com/nunit/nunit3-vs-adapter/issues/1069
