### ISSUE TITLE
Reportportal.Nunit .net is not working

### ISSUE THREAD

**Issue by santhosh-James** [reportportal/agent-net-nunit#49] opened 2019-10-07 14:10 UTC
I did the following thing

1. Installed ReportPortal.Nunit Nuget
2. Added ReportPortal.config.json and copy to the Output directory
3.Added ReportPortal.addins and paste ReportPortal.NUnitExtension.dll inside it
4. Verified the url and uuid in the ReportPortal.config.json

The .net(4.6.1) is not integrating with the reportportal.io.   What is missing here? 

It is perfectly working with .net specflow and .net core nunit. But not with .net nunit.

**Comment by nvborisenko** [comment] 2019-10-07 18:26
@santhosh-James is it duplicate of https://github.com/reportportal/agent-net-nunit/issues/48?

**Comment by nvborisenko** [comment] 2019-10-23 18:46
No activity, closing.

**Closed by nvborisenko** 2019-10-23 18:46 UTC
